title: Feeling Good Book Club
description: A warm corner for our reading journey through the science of happiness
url: "https://gwinsbookclub.eric-metcalf.me"
baseurl: ""

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
